# https://pypi.org/project/dj-command/

[[commands]]
name = "r"
execute = "poetry run ./manage.py runserver 0:8000"
long_running = true

name = "sb"
execute = "poetry run sphinx-build -b html source docs"

name = "sa"
execute = "poetry run sphinx-autobuild -b html source docs"
