# https://pypi.org/project/dj-command/

[[commands]]
name = "r"
execute = "poetry run ./manage.py runserver 0:8000"
long_running = true

[[commands]]
name = "sb"
execute = "poetry run sphinx-build -E -a -b dirhtml source docs"

[[commands]]
name = "sa"
execute = "poetry run sphinx-autobuild -b dirhtml source docs"
long_running = true

[[commands]]
name = "sp"
execute = "poetry run sphinx-build -E -a -b pdf source docs"
