[tool.poetry]
name = "django-unicorn.com"
version = "0.1.0"
description = "Documentation of django-unicorn"
authors = ["Adam Hill"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
django = "^3.0.8"
django-annoying = "^0.10.6"
python-dotenv = "^0.14.0"
gunicorn = "^20.0.4"
whitenoise = "^5.1.0"
django-compressor = "^2.4"
"calmjs.parse" = "^1.2.5"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.3"
isort = "^5.1.1"
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
